services:
  app:
    build: .
    container_name: app-pr-${PR_NUMBER}
    ports:
      - "${PORT}:3000"
    environment:
      PR_NUMBER: ${PR_NUMBER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-pr-${PR_NUMBER}.rule=Host(`pr-${PR_NUMBER}.mypreviews.online`)"
      - "traefik.http.routers.app-pr-${PR_NUMBER}.entrypoints=web"
      - "traefik.http.services.app-pr-${PR_NUMBER}.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true
